package de.hahn.blog.dumpqueryparameter2.model.adfbc.views;

import de.hahn.blog.dumpqueryparameter2.model.adfbc.base.BaseViewObjectImpl;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 06 16:31:40 CEST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountriesViewImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CountriesViewImpl() {
    }
}

