package de.hahn.blog.dumpqueryparameter2.model.adfbc.views;

import de.hahn.blog.dumpqueryparameter2.model.adfbc.base.BaseViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Jun 06 16:33:24 CEST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionsViewImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RegionsViewImpl() {
    }
}

